version: '3'
services: 
    php:
        container_name: php
        build:
            context: .
            dockerfile: ./.docker/php/Dockerfile
        volumes:
            - .:/workspace
            - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
        working_dir: /workspace/src
        tty: true
